### ISSUE TITLE
some discrepancies in the numbers from english database

### ISSUE THREAD

**Issue by freekorea** [freedomfighter2022/koreaelection2020#1]
When I followed Prof. Mebane's paper, I found out that the data came from here. 
And I found some discrepancies in data from "korea_election_regional_21_eng.sqlite"
e.g) jongro prevote_in case(uid 13332 from area4 table). Specifically, "sum_invalid"(or "sum_novote") are actually not 1(or 7) but 17(or 1).

===
미베인 교수의 논문을 읽다가 데이터가 여기서 나왔다는 사실을 알았는데요.
"korea_election_regional_21_eng.sqlite"의 데이터에서 조금 불일치하는 것을 보았습니다.
예를들어 종로구의 사전투표에서 무효표와 기권표는 실제로는 각각 17/1 표지만 data 상에는 1/7표로 나와있더라고요.

p.s. 오늘 기자회견 보고 궁금해져서 논문을 읽고있는데 하나씩 따라가보다가 여기까지 왔습니다. 자료를 번역해주신 것 감사하게 생각하고 있습니다.

**Comment by freedomfighter2022** [comment]
@freekorea 알려주셔서 감사드립니다. 선관위 엑셀 파일에 히든 컬럼들이 있었는데 그것들이 제대로 처리되지 못하여 오류가 발생했습니다. num_invalid 와 num_novote 를 수정하여 다시 업로드하였습니다. 검토해 주시면 감사드리겠습니다. 미베인교수께도 연락드리겠습니다.

**Comment by freedomfighter2022** [comment]
@freekorea 미베인 교수의 연구에서는 num_invalid 와 num_novote 가 사용되지 않았다고 하니 일단 오류가 있던 컬럼들이 지금까지 발표된 연구결과에는 영향을 미치지 않은 듯 합니다.
